package model.applicationModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 18:06:42 IST 2023
// ---------------------------------------------------------------------
public interface WholeSaleProcessAM extends ApplicationModule
{
    String createTransBuItemType();

  String createTransBuCustAcctMapping();
}
