package model.View;

import model.Enitity.XxwsHarItemTypeAcctEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 15:39:31 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsHarItemTypeAcctVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SetupId {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getSetupId();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setSetupId((Number)value);
            }
        }
        ,
        BuId {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getBuId();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setBuId((Number)value);
            }
        }
        ,
        ItemTypeCode {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getItemTypeCode();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setItemTypeCode((String)value);
            }
        }
        ,
        CogsAccnt {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getCogsAccnt();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setCogsAccnt((Number)value);
            }
        }
        ,
        RevenueAccnt {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getRevenueAccnt();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setRevenueAccnt((Number)value);
            }
        }
        ,
        StartDate {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getStartDate();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getEndDate();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(XxwsHarItemTypeAcctVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxwsHarItemTypeAcctVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxwsHarItemTypeAcctVORowImpl object);

        public abstract void put(XxwsHarItemTypeAcctVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SETUPID = AttributesEnum.SetupId.index();
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int ITEMTYPECODE = AttributesEnum.ItemTypeCode.index();
    public static final int COGSACCNT = AttributesEnum.CogsAccnt.index();
    public static final int REVENUEACCNT = AttributesEnum.RevenueAccnt.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxwsHarItemTypeAcctVORowImpl() {
    }

    /**
     * Gets XxwsHarItemTypeAcctEO entity object.
     * @return the XxwsHarItemTypeAcctEO
     */
    public XxwsHarItemTypeAcctEOImpl getXxwsHarItemTypeAcctEO() {
        return (XxwsHarItemTypeAcctEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for SETUP_ID using the alias name SetupId.
     * @return the SETUP_ID
     */
    public Number getSetupId() {
        return (Number) getAttributeInternal(SETUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for SETUP_ID using the alias name SetupId.
     * @param value value to set the SETUP_ID
     */
    public void setSetupId(Number value) {
        setAttributeInternal(SETUPID, value);
    }

    /**
     * Gets the attribute value for BU_ID using the alias name BuId.
     * @return the BU_ID
     */
    public Number getBuId() {
        return (Number) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
     * @param value value to set the BU_ID
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for ITEM_TYPE_CODE using the alias name ItemTypeCode.
     * @return the ITEM_TYPE_CODE
     */
    public String getItemTypeCode() {
        return (String) getAttributeInternal(ITEMTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_TYPE_CODE using the alias name ItemTypeCode.
     * @param value value to set the ITEM_TYPE_CODE
     */
    public void setItemTypeCode(String value) {
        setAttributeInternal(ITEMTYPECODE, value);
    }

    /**
     * Gets the attribute value for COGS_ACCNT using the alias name CogsAccnt.
     * @return the COGS_ACCNT
     */
    public Number getCogsAccnt() {
        return (Number) getAttributeInternal(COGSACCNT);
    }

    /**
     * Sets <code>value</code> as attribute value for COGS_ACCNT using the alias name CogsAccnt.
     * @param value value to set the COGS_ACCNT
     */
    public void setCogsAccnt(Number value) {
        setAttributeInternal(COGSACCNT, value);
    }

    /**
     * Gets the attribute value for REVENUE_ACCNT using the alias name RevenueAccnt.
     * @return the REVENUE_ACCNT
     */
    public Number getRevenueAccnt() {
        return (Number) getAttributeInternal(REVENUEACCNT);
    }

    /**
     * Sets <code>value</code> as attribute value for REVENUE_ACCNT using the alias name RevenueAccnt.
     * @param value value to set the REVENUE_ACCNT
     */
    public void setRevenueAccnt(Number value) {
        setAttributeInternal(REVENUEACCNT, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
