package model.LOV;

import model.Enitity.XxwsVasCustomerDetailsEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 18:01:16 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsVasCustomerNameLOVRowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    AccountStatus
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getAccountStatus();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setAccountStatus((String)value);
      }
    }
    ,
    AccountType
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getAccountType();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setAccountType((String)value);
      }
    }
    ,
    BuId
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getBuId();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setBuId((Number)value);
      }
    }
    ,
    CustAccountId
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getCustAccountId();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setCustAccountId((Number)value);
      }
    }
    ,
    CustomerId
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getCustomerId();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setCustomerId((Number)value);
      }
    }
    ,
    CustomerName
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getCustomerName();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setCustomerName((String)value);
      }
    }
    ,
    CustomerNumber
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getCustomerNumber();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setCustomerNumber((String)value);
      }
    }
    ,
    PartyStatus
    {
      public Object get(XxwsVasCustomerNameLOVRowImpl obj)
      {
        return obj.getPartyStatus();
      }

      public void put(XxwsVasCustomerNameLOVRowImpl obj, Object value)
      {
        obj.setPartyStatus((String)value);
      }
    }
    ;
    static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(XxwsVasCustomerNameLOVRowImpl object);

    public abstract void put(XxwsVasCustomerNameLOVRowImpl object,
                             Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int ACCOUNTSTATUS = AttributesEnum.AccountStatus.index();
  public static final int ACCOUNTTYPE = AttributesEnum.AccountType.index();
  public static final int BUID = AttributesEnum.BuId.index();
  public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
  public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
  public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
  public static final int CUSTOMERNUMBER = AttributesEnum.CustomerNumber.index();
  public static final int PARTYSTATUS = AttributesEnum.PartyStatus.index();

  /**
   * This is the default constructor (do not remove).
   */
  public XxwsVasCustomerNameLOVRowImpl()
  {
  }

  /**
   * Gets XxwsVasCustomerDetailsEO entity object.
   * @return the XxwsVasCustomerDetailsEO
   */
  public XxwsVasCustomerDetailsEOImpl getXxwsVasCustomerDetailsEO()
  {
    return (XxwsVasCustomerDetailsEOImpl) getEntity(0);
  }

  /**
   * Gets the attribute value for ACCOUNT_STATUS using the alias name AccountStatus.
   * @return the ACCOUNT_STATUS
   */
  public String getAccountStatus()
  {
    return (String) getAttributeInternal(ACCOUNTSTATUS);
  }

  /**
   * Sets <code>value</code> as attribute value for ACCOUNT_STATUS using the alias name AccountStatus.
   * @param value value to set the ACCOUNT_STATUS
   */
  public void setAccountStatus(String value)
  {
    setAttributeInternal(ACCOUNTSTATUS, value);
  }

  /**
   * Gets the attribute value for ACCOUNT_TYPE using the alias name AccountType.
   * @return the ACCOUNT_TYPE
   */
  public String getAccountType()
  {
    return (String) getAttributeInternal(ACCOUNTTYPE);
  }

  /**
   * Sets <code>value</code> as attribute value for ACCOUNT_TYPE using the alias name AccountType.
   * @param value value to set the ACCOUNT_TYPE
   */
  public void setAccountType(String value)
  {
    setAttributeInternal(ACCOUNTTYPE, value);
  }

  /**
   * Gets the attribute value for BU_ID using the alias name BuId.
   * @return the BU_ID
   */
  public Number getBuId()
  {
    return (Number) getAttributeInternal(BUID);
  }

  /**
   * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
   * @param value value to set the BU_ID
   */
  public void setBuId(Number value)
  {
    setAttributeInternal(BUID, value);
  }

  /**
   * Gets the attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId.
   * @return the CUST_ACCOUNT_ID
   */
  public Number getCustAccountId()
  {
    return (Number) getAttributeInternal(CUSTACCOUNTID);
  }

  /**
   * Sets <code>value</code> as attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId.
   * @param value value to set the CUST_ACCOUNT_ID
   */
  public void setCustAccountId(Number value)
  {
    setAttributeInternal(CUSTACCOUNTID, value);
  }

  /**
   * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
   * @return the CUSTOMER_ID
   */
  public Number getCustomerId()
  {
    return (Number) getAttributeInternal(CUSTOMERID);
  }

  /**
   * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
   * @param value value to set the CUSTOMER_ID
   */
  public void setCustomerId(Number value)
  {
    setAttributeInternal(CUSTOMERID, value);
  }

  /**
   * Gets the attribute value for CUSTOMER_NAME using the alias name CustomerName.
   * @return the CUSTOMER_NAME
   */
  public String getCustomerName()
  {
    return (String) getAttributeInternal(CUSTOMERNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for CUSTOMER_NAME using the alias name CustomerName.
   * @param value value to set the CUSTOMER_NAME
   */
  public void setCustomerName(String value)
  {
    setAttributeInternal(CUSTOMERNAME, value);
  }

  /**
   * Gets the attribute value for CUSTOMER_NUMBER using the alias name CustomerNumber.
   * @return the CUSTOMER_NUMBER
   */
  public String getCustomerNumber()
  {
    return (String) getAttributeInternal(CUSTOMERNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for CUSTOMER_NUMBER using the alias name CustomerNumber.
   * @param value value to set the CUSTOMER_NUMBER
   */
  public void setCustomerNumber(String value)
  {
    setAttributeInternal(CUSTOMERNUMBER, value);
  }

  /**
   * Gets the attribute value for PARTY_STATUS using the alias name PartyStatus.
   * @return the PARTY_STATUS
   */
  public String getPartyStatus()
  {
    return (String) getAttributeInternal(PARTYSTATUS);
  }

  /**
   * Sets <code>value</code> as attribute value for PARTY_STATUS using the alias name PartyStatus.
   * @param value value to set the PARTY_STATUS
   */
  public void setPartyStatus(String value)
  {
    setAttributeInternal(PARTYSTATUS, value);
  }


  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
