package model.View;

import model.Enitity.XxwsVasCustAcctMappingEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 16:08:53 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsVasCustAcctMappingVORowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    BuId
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getBuId();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setBuId((Number)value);
      }
    }
    ,
    CogsCcid
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getCogsCcid();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setCogsCcid((Number)value);
      }
    }
    ,
    CreatedBy
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getCreatedBy();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setCreatedBy((String)value);
      }
    }
    ,
    CreationDate
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getCreationDate();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setCreationDate((Date)value);
      }
    }
    ,
    CustAccountId
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getCustAccountId();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setCustAccountId((Number)value);
      }
    }
    ,
    DiscountCcid
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getDiscountCcid();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setDiscountCcid((Number)value);
      }
    }
    ,
    EndDate
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getEndDate();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setEndDate((Date)value);
      }
    }
    ,
    LastUpdateDate
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getLastUpdateDate();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setLastUpdateDate((Date)value);
      }
    }
    ,
    LastUpdatedBy
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getLastUpdatedBy();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setLastUpdatedBy((String)value);
      }
    }
    ,
    ObjectVersionNumber
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getObjectVersionNumber();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setObjectVersionNumber((Number)value);
      }
    }
    ,
    ReceivableCcid
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getReceivableCcid();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setReceivableCcid((Number)value);
      }
    }
    ,
    SalesCcid
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getSalesCcid();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setSalesCcid((Number)value);
      }
    }
    ,
    SetupId
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getSetupId();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setSetupId((Number)value);
      }
    }
    ,
    SponsorshipCcid
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getSponsorshipCcid();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setSponsorshipCcid((Number)value);
      }
    }
    ,
    StartDate
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getStartDate();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setStartDate((Date)value);
      }
    }
    ,
    TaxCode
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getTaxCode();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setTaxCode((String)value);
      }
    }
    ,
    XxwsVasCustomerNameLOV1
    {
      public Object get(XxwsVasCustAcctMappingVORowImpl obj)
      {
        return obj.getXxwsVasCustomerNameLOV1();
      }

      public void put(XxwsVasCustAcctMappingVORowImpl obj, Object value)
      {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(XxwsVasCustAcctMappingVORowImpl object);

    public abstract void put(XxwsVasCustAcctMappingVORowImpl object,
                             Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int BUID = AttributesEnum.BuId.index();
  public static final int COGSCCID = AttributesEnum.CogsCcid.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
  public static final int DISCOUNTCCID = AttributesEnum.DiscountCcid.index();
  public static final int ENDDATE = AttributesEnum.EndDate.index();
  public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
  public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
  public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
  public static final int RECEIVABLECCID = AttributesEnum.ReceivableCcid.index();
  public static final int SALESCCID = AttributesEnum.SalesCcid.index();
  public static final int SETUPID = AttributesEnum.SetupId.index();
  public static final int SPONSORSHIPCCID = AttributesEnum.SponsorshipCcid.index();
  public static final int STARTDATE = AttributesEnum.StartDate.index();
  public static final int TAXCODE = AttributesEnum.TaxCode.index();
  public static final int XXWSVASCUSTOMERNAMELOV1 = AttributesEnum.XxwsVasCustomerNameLOV1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public XxwsVasCustAcctMappingVORowImpl()
  {
  }

  /**
   * Gets XxwsVasCustAcctMappingEO entity object.
   * @return the XxwsVasCustAcctMappingEO
   */
  public XxwsVasCustAcctMappingEOImpl getXxwsVasCustAcctMappingEO()
  {
    return (XxwsVasCustAcctMappingEOImpl) getEntity(0);
  }

  /**
   * Gets the attribute value for BU_ID using the alias name BuId.
   * @return the BU_ID
   */
  public Number getBuId()
  {
    return (Number) getAttributeInternal(BUID);
  }

  /**
   * Sets <code>value</code> as attribute value for BU_ID using the alias name BuId.
   * @param value value to set the BU_ID
   */
  public void setBuId(Number value)
  {
    setAttributeInternal(BUID, value);
  }

  /**
   * Gets the attribute value for COGS_CCID using the alias name CogsCcid.
   * @return the COGS_CCID
   */
  public Number getCogsCcid()
  {
    return (Number) getAttributeInternal(COGSCCID);
  }

  /**
   * Sets <code>value</code> as attribute value for COGS_CCID using the alias name CogsCcid.
   * @param value value to set the COGS_CCID
   */
  public void setCogsCcid(Number value)
  {
    setAttributeInternal(COGSCCID, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public String getCreatedBy()
  {
    return (String) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId.
   * @return the CUST_ACCOUNT_ID
   */
  public Number getCustAccountId()
  {
    return (Number) getAttributeInternal(CUSTACCOUNTID);
  }

  /**
   * Sets <code>value</code> as attribute value for CUST_ACCOUNT_ID using the alias name CustAccountId.
   * @param value value to set the CUST_ACCOUNT_ID
   */
  public void setCustAccountId(Number value)
  {
    setAttributeInternal(CUSTACCOUNTID, value);
  }

  /**
   * Gets the attribute value for DISCOUNT_CCID using the alias name DiscountCcid.
   * @return the DISCOUNT_CCID
   */
  public Number getDiscountCcid()
  {
    return (Number) getAttributeInternal(DISCOUNTCCID);
  }

  /**
   * Sets <code>value</code> as attribute value for DISCOUNT_CCID using the alias name DiscountCcid.
   * @param value value to set the DISCOUNT_CCID
   */
  public void setDiscountCcid(Number value)
  {
    setAttributeInternal(DISCOUNTCCID, value);
  }

  /**
   * Gets the attribute value for END_DATE using the alias name EndDate.
   * @return the END_DATE
   */
  public Date getEndDate()
  {
    return (Date) getAttributeInternal(ENDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
   * @param value value to set the END_DATE
   */
  public void setEndDate(Date value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**
   * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
   * @return the LAST_UPDATE_DATE
   */
  public Date getLastUpdateDate()
  {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
   * @param value value to set the LAST_UPDATE_DATE
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
   * @return the LAST_UPDATED_BY
   */
  public String getLastUpdatedBy()
  {
    return (String) getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
   * @param value value to set the LAST_UPDATED_BY
   */
  public void setLastUpdatedBy(String value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
   * @return the OBJECT_VERSION_NUMBER
   */
  public Number getObjectVersionNumber()
  {
    return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
   * @param value value to set the OBJECT_VERSION_NUMBER
   */
  public void setObjectVersionNumber(Number value)
  {
    setAttributeInternal(OBJECTVERSIONNUMBER, value);
  }

  /**
   * Gets the attribute value for RECEIVABLE_CCID using the alias name ReceivableCcid.
   * @return the RECEIVABLE_CCID
   */
  public Number getReceivableCcid()
  {
    return (Number) getAttributeInternal(RECEIVABLECCID);
  }

  /**
   * Sets <code>value</code> as attribute value for RECEIVABLE_CCID using the alias name ReceivableCcid.
   * @param value value to set the RECEIVABLE_CCID
   */
  public void setReceivableCcid(Number value)
  {
    setAttributeInternal(RECEIVABLECCID, value);
  }

  /**
   * Gets the attribute value for SALES_CCID using the alias name SalesCcid.
   * @return the SALES_CCID
   */
  public Number getSalesCcid()
  {
    return (Number) getAttributeInternal(SALESCCID);
  }

  /**
   * Sets <code>value</code> as attribute value for SALES_CCID using the alias name SalesCcid.
   * @param value value to set the SALES_CCID
   */
  public void setSalesCcid(Number value)
  {
    setAttributeInternal(SALESCCID, value);
  }

  /**
   * Gets the attribute value for SETUP_ID using the alias name SetupId.
   * @return the SETUP_ID
   */
  public Number getSetupId()
  {
    return (Number) getAttributeInternal(SETUPID);
  }

  /**
   * Sets <code>value</code> as attribute value for SETUP_ID using the alias name SetupId.
   * @param value value to set the SETUP_ID
   */
  public void setSetupId(Number value)
  {
    setAttributeInternal(SETUPID, value);
  }

  /**
   * Gets the attribute value for SPONSORSHIP_CCID using the alias name SponsorshipCcid.
   * @return the SPONSORSHIP_CCID
   */
  public Number getSponsorshipCcid()
  {
    return (Number) getAttributeInternal(SPONSORSHIPCCID);
  }

  /**
   * Sets <code>value</code> as attribute value for SPONSORSHIP_CCID using the alias name SponsorshipCcid.
   * @param value value to set the SPONSORSHIP_CCID
   */
  public void setSponsorshipCcid(Number value)
  {
    setAttributeInternal(SPONSORSHIPCCID, value);
  }

  /**
   * Gets the attribute value for START_DATE using the alias name StartDate.
   * @return the START_DATE
   */
  public Date getStartDate()
  {
    return (Date) getAttributeInternal(STARTDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
   * @param value value to set the START_DATE
   */
  public void setStartDate(Date value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**
   * Gets the attribute value for TAX_CODE using the alias name TaxCode.
   * @return the TAX_CODE
   */
  public String getTaxCode()
  {
    return (String) getAttributeInternal(TAXCODE);
  }

  /**
   * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
   * @param value value to set the TAX_CODE
   */
  public void setTaxCode(String value)
  {
    setAttributeInternal(TAXCODE, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> XxwsVasCustomerNameLOV1.
   */
  public RowSet getXxwsVasCustomerNameLOV1()
  {
    return (RowSet) getAttributeInternal(XXWSVASCUSTOMERNAMELOV1);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
