package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 18:01:16 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsVasCustomerNameLOVImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public XxwsVasCustomerNameLOVImpl()
  {
  }
}
