package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 16:26:54 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsBusinessUnitLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxwsBusinessUnitLOVImpl() {
    }
}
