package model.LOV;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 16:26:54 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsBusinessUnitLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BuId {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getBuId();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setBuId((Number)value);
            }
        }
        ,
        BuName {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getBuName();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setBuName((String)value);
            }
        }
        ,
        BuCode {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getBuCode();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setBuCode((String)value);
            }
        }
        ,
        StartDate {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getStartDate();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getEndDate();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        CurrencyCode {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getCurrencyCode();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setCurrencyCode((String)value);
            }
        }
        ,
        CountryCode {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getCountryCode();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setCountryCode((String)value);
            }
        }
        ,
        LedgerId {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getLedgerId();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setLedgerId((Number)value);
            }
        }
        ,
        SetId {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getSetId();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setSetId((Number)value);
            }
        }
        ,
        TrnNumber {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getTrnNumber();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setTrnNumber((Number)value);
            }
        }
        ,
        LegalEntityName {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getLegalEntityName();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setLegalEntityName((String)value);
            }
        }
        ,
        EntityCcId {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getEntityCcId();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setEntityCcId((Number)value);
            }
        }
        ,
        LedgerName {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getLedgerName();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setLedgerName((String)value);
            }
        }
        ,
        TaxFlag {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getTaxFlag();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setTaxFlag((String)value);
            }
        }
        ,
        DefaultSetId {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getDefaultSetId();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setDefaultSetId((Number)value);
            }
        }
        ,
        LegalEntityNameLookup {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getLegalEntityNameLookup();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setLegalEntityNameLookup((String)value);
            }
        }
        ,
        LegalEntityAddress {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getLegalEntityAddress();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setLegalEntityAddress((String)value);
            }
        }
        ,
        BuRepCode {
            public Object get(XxwsBusinessUnitLOVRowImpl obj) {
                return obj.getBuRepCode();
            }

            public void put(XxwsBusinessUnitLOVRowImpl obj, Object value) {
                obj.setBuRepCode((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxwsBusinessUnitLOVRowImpl object);

        public abstract void put(XxwsBusinessUnitLOVRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BUID = AttributesEnum.BuId.index();
    public static final int BUNAME = AttributesEnum.BuName.index();
    public static final int BUCODE = AttributesEnum.BuCode.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int LEDGERID = AttributesEnum.LedgerId.index();
    public static final int SETID = AttributesEnum.SetId.index();
    public static final int TRNNUMBER = AttributesEnum.TrnNumber.index();
    public static final int LEGALENTITYNAME = AttributesEnum.LegalEntityName.index();
    public static final int ENTITYCCID = AttributesEnum.EntityCcId.index();
    public static final int LEDGERNAME = AttributesEnum.LedgerName.index();
    public static final int TAXFLAG = AttributesEnum.TaxFlag.index();
    public static final int DEFAULTSETID = AttributesEnum.DefaultSetId.index();
    public static final int LEGALENTITYNAMELOOKUP = AttributesEnum.LegalEntityNameLookup.index();
    public static final int LEGALENTITYADDRESS = AttributesEnum.LegalEntityAddress.index();
    public static final int BUREPCODE = AttributesEnum.BuRepCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxwsBusinessUnitLOVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BuId.
     * @return the BuId
     */
    public Number getBuId() {
        return (Number) getAttributeInternal(BUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuId.
     * @param value value to set the  BuId
     */
    public void setBuId(Number value) {
        setAttributeInternal(BUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuName.
     * @return the BuName
     */
    public String getBuName() {
        return (String) getAttributeInternal(BUNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuName.
     * @param value value to set the  BuName
     */
    public void setBuName(String value) {
        setAttributeInternal(BUNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuCode.
     * @return the BuCode
     */
    public String getBuCode() {
        return (String) getAttributeInternal(BUCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuCode.
     * @param value value to set the  BuCode
     */
    public void setBuCode(String value) {
        setAttributeInternal(BUCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StartDate.
     * @return the StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StartDate.
     * @param value value to set the  StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EndDate.
     * @return the EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndDate.
     * @param value value to set the  EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyCode.
     * @return the CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode.
     * @param value value to set the  CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CountryCode.
     * @param value value to set the  CountryCode
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LedgerId.
     * @return the LedgerId
     */
    public Number getLedgerId() {
        return (Number) getAttributeInternal(LEDGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LedgerId.
     * @param value value to set the  LedgerId
     */
    public void setLedgerId(Number value) {
        setAttributeInternal(LEDGERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SetId.
     * @return the SetId
     */
    public Number getSetId() {
        return (Number) getAttributeInternal(SETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SetId.
     * @param value value to set the  SetId
     */
    public void setSetId(Number value) {
        setAttributeInternal(SETID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TrnNumber.
     * @return the TrnNumber
     */
    public Number getTrnNumber() {
        return (Number) getAttributeInternal(TRNNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TrnNumber.
     * @param value value to set the  TrnNumber
     */
    public void setTrnNumber(Number value) {
        setAttributeInternal(TRNNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegalEntityName.
     * @return the LegalEntityName
     */
    public String getLegalEntityName() {
        return (String) getAttributeInternal(LEGALENTITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegalEntityName.
     * @param value value to set the  LegalEntityName
     */
    public void setLegalEntityName(String value) {
        setAttributeInternal(LEGALENTITYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EntityCcId.
     * @return the EntityCcId
     */
    public Number getEntityCcId() {
        return (Number) getAttributeInternal(ENTITYCCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EntityCcId.
     * @param value value to set the  EntityCcId
     */
    public void setEntityCcId(Number value) {
        setAttributeInternal(ENTITYCCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LedgerName.
     * @return the LedgerName
     */
    public String getLedgerName() {
        return (String) getAttributeInternal(LEDGERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LedgerName.
     * @param value value to set the  LedgerName
     */
    public void setLedgerName(String value) {
        setAttributeInternal(LEDGERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxFlag.
     * @return the TaxFlag
     */
    public String getTaxFlag() {
        return (String) getAttributeInternal(TAXFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxFlag.
     * @param value value to set the  TaxFlag
     */
    public void setTaxFlag(String value) {
        setAttributeInternal(TAXFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DefaultSetId.
     * @return the DefaultSetId
     */
    public Number getDefaultSetId() {
        return (Number) getAttributeInternal(DEFAULTSETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DefaultSetId.
     * @param value value to set the  DefaultSetId
     */
    public void setDefaultSetId(Number value) {
        setAttributeInternal(DEFAULTSETID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegalEntityNameLookup.
     * @return the LegalEntityNameLookup
     */
    public String getLegalEntityNameLookup() {
        return (String) getAttributeInternal(LEGALENTITYNAMELOOKUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegalEntityNameLookup.
     * @param value value to set the  LegalEntityNameLookup
     */
    public void setLegalEntityNameLookup(String value) {
        setAttributeInternal(LEGALENTITYNAMELOOKUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegalEntityAddress.
     * @return the LegalEntityAddress
     */
    public String getLegalEntityAddress() {
        return (String) getAttributeInternal(LEGALENTITYADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegalEntityAddress.
     * @param value value to set the  LegalEntityAddress
     */
    public void setLegalEntityAddress(String value) {
        setAttributeInternal(LEGALENTITYADDRESS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuRepCode.
     * @return the BuRepCode
     */
    public String getBuRepCode() {
        return (String) getAttributeInternal(BUREPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuRepCode.
     * @param value value to set the  BuRepCode
     */
    public void setBuRepCode(String value) {
        setAttributeInternal(BUREPCODE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
