package model.applicationModule;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 16:13:15 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WholeSaleProcessAMDefImpl
  extends ApplicationModuleDefImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public WholeSaleProcessAMDefImpl()
  {
  }
}
