package model.Enitity;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 17:58:26 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsVasCustomerDetailsEOImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    CustomerName
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getCustomerName();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setCustomerName((String)value);
      }
    }
    ,
    CustomerNumber
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getCustomerNumber();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setCustomerNumber((String)value);
      }
    }
    ,
    CustAccountId
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getCustAccountId();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setCustAccountId((Number)value);
      }
    }
    ,
    BuId
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getBuId();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setBuId((Number)value);
      }
    }
    ,
    CustomerId
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getCustomerId();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setCustomerId((Number)value);
      }
    }
    ,
    AccountType
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getAccountType();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setAccountType((String)value);
      }
    }
    ,
    PartyStatus
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getPartyStatus();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setPartyStatus((String)value);
      }
    }
    ,
    AccountStatus
    {
      public Object get(XxwsVasCustomerDetailsEOImpl obj)
      {
        return obj.getAccountStatus();
      }

      public void put(XxwsVasCustomerDetailsEOImpl obj, Object value)
      {
        obj.setAccountStatus((String)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(XxwsVasCustomerDetailsEOImpl object);

    public abstract void put(XxwsVasCustomerDetailsEOImpl object,
                             Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
  public static final int CUSTOMERNUMBER = AttributesEnum.CustomerNumber.index();
  public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
  public static final int BUID = AttributesEnum.BuId.index();
  public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
  public static final int ACCOUNTTYPE = AttributesEnum.AccountType.index();
  public static final int PARTYSTATUS = AttributesEnum.PartyStatus.index();
  public static final int ACCOUNTSTATUS = AttributesEnum.AccountStatus.index();

  /**
   * This is the default constructor (do not remove).
   */
  public XxwsVasCustomerDetailsEOImpl()
  {
  }

  /**
   * Gets the attribute value for CustomerName, using the alias name CustomerName.
   * @return the CustomerName
   */
  public String getCustomerName()
  {
    return (String)getAttributeInternal(CUSTOMERNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for CustomerName.
   * @param value value to set the CustomerName
   */
  public void setCustomerName(String value)
  {
    setAttributeInternal(CUSTOMERNAME, value);
  }

  /**
   * Gets the attribute value for CustomerNumber, using the alias name CustomerNumber.
   * @return the CustomerNumber
   */
  public String getCustomerNumber()
  {
    return (String)getAttributeInternal(CUSTOMERNUMBER);
  }

  /**
   * Sets <code>value</code> as the attribute value for CustomerNumber.
   * @param value value to set the CustomerNumber
   */
  public void setCustomerNumber(String value)
  {
    setAttributeInternal(CUSTOMERNUMBER, value);
  }

  /**
   * Gets the attribute value for CustAccountId, using the alias name CustAccountId.
   * @return the CustAccountId
   */
  public Number getCustAccountId()
  {
    return (Number)getAttributeInternal(CUSTACCOUNTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for CustAccountId.
   * @param value value to set the CustAccountId
   */
  public void setCustAccountId(Number value)
  {
    setAttributeInternal(CUSTACCOUNTID, value);
  }

  /**
   * Gets the attribute value for BuId, using the alias name BuId.
   * @return the BuId
   */
  public Number getBuId()
  {
    return (Number)getAttributeInternal(BUID);
  }

  /**
   * Sets <code>value</code> as the attribute value for BuId.
   * @param value value to set the BuId
   */
  public void setBuId(Number value)
  {
    setAttributeInternal(BUID, value);
  }

  /**
   * Gets the attribute value for CustomerId, using the alias name CustomerId.
   * @return the CustomerId
   */
  public Number getCustomerId()
  {
    return (Number)getAttributeInternal(CUSTOMERID);
  }

  /**
   * Sets <code>value</code> as the attribute value for CustomerId.
   * @param value value to set the CustomerId
   */
  public void setCustomerId(Number value)
  {
    setAttributeInternal(CUSTOMERID, value);
  }

  /**
   * Gets the attribute value for AccountType, using the alias name AccountType.
   * @return the AccountType
   */
  public String getAccountType()
  {
    return (String)getAttributeInternal(ACCOUNTTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for AccountType.
   * @param value value to set the AccountType
   */
  public void setAccountType(String value)
  {
    setAttributeInternal(ACCOUNTTYPE, value);
  }

  /**
   * Gets the attribute value for PartyStatus, using the alias name PartyStatus.
   * @return the PartyStatus
   */
  public String getPartyStatus()
  {
    return (String)getAttributeInternal(PARTYSTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for PartyStatus.
   * @param value value to set the PartyStatus
   */
  public void setPartyStatus(String value)
  {
    setAttributeInternal(PARTYSTATUS, value);
  }

  /**
   * Gets the attribute value for AccountStatus, using the alias name AccountStatus.
   * @return the AccountStatus
   */
  public String getAccountStatus()
  {
    return (String)getAttributeInternal(ACCOUNTSTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for AccountStatus.
   * @param value value to set the AccountStatus
   */
  public void setAccountStatus(String value)
  {
    setAttributeInternal(ACCOUNTSTATUS, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @param customerNumber key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(String customerNumber)
  {
    return new Key(new Object[]{customerNumber});
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.Enitity.XxwsVasCustomerDetailsEO");
  }
}
