package model.Enitity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 01 16:05:32 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxwsVasCustAcctMappingEOImpl
  extends EntityImpl
{
  protected void create(AttributeList attributeList)
    {
      super.create(attributeList);
      SequenceImpl seq =
        new SequenceImpl("XXWS_VAS_CUST_ACCT_MApping_S", this.getDBTransaction());
      setSetupId(seq.getSequenceNumber());

    }
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    SetupId
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getSetupId();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setSetupId((Number)value);
      }
    }
    ,
    BuId
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getBuId();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setBuId((Number)value);
      }
    }
    ,
    CustAccountId
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getCustAccountId();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setCustAccountId((Number)value);
      }
    }
    ,
    CogsCcid
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getCogsCcid();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setCogsCcid((Number)value);
      }
    }
    ,
    SalesCcid
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getSalesCcid();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setSalesCcid((Number)value);
      }
    }
    ,
    ReceivableCcid
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getReceivableCcid();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setReceivableCcid((Number)value);
      }
    }
    ,
    DiscountCcid
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getDiscountCcid();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setDiscountCcid((Number)value);
      }
    }
    ,
    SponsorshipCcid
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getSponsorshipCcid();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setSponsorshipCcid((Number)value);
      }
    }
    ,
    TaxCode
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getTaxCode();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setTaxCode((String)value);
      }
    }
    ,
    StartDate
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getStartDate();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setStartDate((Date)value);
      }
    }
    ,
    EndDate
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getEndDate();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setEndDate((Date)value);
      }
    }
    ,
    CreatedBy
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getCreatedBy();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setCreatedBy((String)value);
      }
    }
    ,
    CreationDate
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getCreationDate();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setCreationDate((Date)value);
      }
    }
    ,
    LastUpdatedBy
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getLastUpdatedBy();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setLastUpdatedBy((String)value);
      }
    }
    ,
    LastUpdateDate
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getLastUpdateDate();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setLastUpdateDate((Date)value);
      }
    }
    ,
    ObjectVersionNumber
    {
      public Object get(XxwsVasCustAcctMappingEOImpl obj)
      {
        return obj.getObjectVersionNumber();
      }

      public void put(XxwsVasCustAcctMappingEOImpl obj, Object value)
      {
        obj.setObjectVersionNumber((Number)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(XxwsVasCustAcctMappingEOImpl object);

    public abstract void put(XxwsVasCustAcctMappingEOImpl object,
                             Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int SETUPID = AttributesEnum.SetupId.index();
  public static final int BUID = AttributesEnum.BuId.index();
  public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
  public static final int COGSCCID = AttributesEnum.CogsCcid.index();
  public static final int SALESCCID = AttributesEnum.SalesCcid.index();
  public static final int RECEIVABLECCID = AttributesEnum.ReceivableCcid.index();
  public static final int DISCOUNTCCID = AttributesEnum.DiscountCcid.index();
  public static final int SPONSORSHIPCCID = AttributesEnum.SponsorshipCcid.index();
  public static final int TAXCODE = AttributesEnum.TaxCode.index();
  public static final int STARTDATE = AttributesEnum.StartDate.index();
  public static final int ENDDATE = AttributesEnum.EndDate.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
  public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
  public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();

  /**
   * This is the default constructor (do not remove).
   */
  public XxwsVasCustAcctMappingEOImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.Enitity.XxwsVasCustAcctMappingEO");
  }

  /**
   * Gets the attribute value for SetupId, using the alias name SetupId.
   * @return the SetupId
   */
  public Number getSetupId()
  {
    return (Number)getAttributeInternal(SETUPID);
  }

  /**
   * Sets <code>value</code> as the attribute value for SetupId.
   * @param value value to set the SetupId
   */
  public void setSetupId(Number value)
  {
    setAttributeInternal(SETUPID, value);
  }

  /**
   * Gets the attribute value for BuId, using the alias name BuId.
   * @return the BuId
   */
  public Number getBuId()
  {
    return (Number)getAttributeInternal(BUID);
  }

  /**
   * Sets <code>value</code> as the attribute value for BuId.
   * @param value value to set the BuId
   */
  public void setBuId(Number value)
  {
    setAttributeInternal(BUID, value);
  }

  /**
   * Gets the attribute value for CustAccountId, using the alias name CustAccountId.
   * @return the CustAccountId
   */
  public Number getCustAccountId()
  {
    return (Number)getAttributeInternal(CUSTACCOUNTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for CustAccountId.
   * @param value value to set the CustAccountId
   */
  public void setCustAccountId(Number value)
  {
    setAttributeInternal(CUSTACCOUNTID, value);
  }

  /**
   * Gets the attribute value for CogsCcid, using the alias name CogsCcid.
   * @return the CogsCcid
   */
  public Number getCogsCcid()
  {
    return (Number)getAttributeInternal(COGSCCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for CogsCcid.
   * @param value value to set the CogsCcid
   */
  public void setCogsCcid(Number value)
  {
    setAttributeInternal(COGSCCID, value);
  }

  /**
   * Gets the attribute value for SalesCcid, using the alias name SalesCcid.
   * @return the SalesCcid
   */
  public Number getSalesCcid()
  {
    return (Number)getAttributeInternal(SALESCCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for SalesCcid.
   * @param value value to set the SalesCcid
   */
  public void setSalesCcid(Number value)
  {
    setAttributeInternal(SALESCCID, value);
  }

  /**
   * Gets the attribute value for ReceivableCcid, using the alias name ReceivableCcid.
   * @return the ReceivableCcid
   */
  public Number getReceivableCcid()
  {
    return (Number)getAttributeInternal(RECEIVABLECCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ReceivableCcid.
   * @param value value to set the ReceivableCcid
   */
  public void setReceivableCcid(Number value)
  {
    setAttributeInternal(RECEIVABLECCID, value);
  }

  /**
   * Gets the attribute value for DiscountCcid, using the alias name DiscountCcid.
   * @return the DiscountCcid
   */
  public Number getDiscountCcid()
  {
    return (Number)getAttributeInternal(DISCOUNTCCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for DiscountCcid.
   * @param value value to set the DiscountCcid
   */
  public void setDiscountCcid(Number value)
  {
    setAttributeInternal(DISCOUNTCCID, value);
  }

  /**
   * Gets the attribute value for SponsorshipCcid, using the alias name SponsorshipCcid.
   * @return the SponsorshipCcid
   */
  public Number getSponsorshipCcid()
  {
    return (Number)getAttributeInternal(SPONSORSHIPCCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for SponsorshipCcid.
   * @param value value to set the SponsorshipCcid
   */
  public void setSponsorshipCcid(Number value)
  {
    setAttributeInternal(SPONSORSHIPCCID, value);
  }

  /**
   * Gets the attribute value for TaxCode, using the alias name TaxCode.
   * @return the TaxCode
   */
  public String getTaxCode()
  {
    return (String)getAttributeInternal(TAXCODE);
  }

  /**
   * Sets <code>value</code> as the attribute value for TaxCode.
   * @param value value to set the TaxCode
   */
  public void setTaxCode(String value)
  {
    setAttributeInternal(TAXCODE, value);
  }

  /**
   * Gets the attribute value for StartDate, using the alias name StartDate.
   * @return the StartDate
   */
  public Date getStartDate()
  {
    return (Date)getAttributeInternal(STARTDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for StartDate.
   * @param value value to set the StartDate
   */
  public void setStartDate(Date value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**
   * Gets the attribute value for EndDate, using the alias name EndDate.
   * @return the EndDate
   */
  public Date getEndDate()
  {
    return (Date)getAttributeInternal(ENDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for EndDate.
   * @param value value to set the EndDate
   */
  public void setEndDate(Date value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the CreatedBy
   */
  public String getCreatedBy()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
   * @return the LastUpdatedBy
   */
  public String getLastUpdatedBy()
  {
    return (String)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for LastUpdatedBy.
   * @param value value to set the LastUpdatedBy
   */
  public void setLastUpdatedBy(String value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
   * @return the LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for LastUpdateDate.
   * @param value value to set the LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
   * @return the ObjectVersionNumber
   */
  public Number getObjectVersionNumber()
  {
    return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
  }

  /**
   * Sets <code>value</code> as the attribute value for ObjectVersionNumber.
   * @param value value to set the ObjectVersionNumber
   */
  public void setObjectVersionNumber(Number value)
  {
    setAttributeInternal(OBJECTVERSIONNUMBER, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @param setupId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Number setupId)
  {
    return new Key(new Object[]{setupId});
  }


}
